#!/bin/bash

maxattempts=-1
attempts=0
if [ "$#" -ne 0 ]; then
    maxattempts=$1
fi

showStatus(){
    newline="\n"
    if [[ $2 == "silent" ]]; then
	newline=""
    fi 
    dt=$(date '+%H:%M:%S.%3N');
    echo -n -e "$dt Wifi Check > $1$newline"
}


doPing(){

    ping 8.8.8.8 -c 4 &> /dev/null

    if [ $? -eq 0 ]; then
        showStatus "Connected!"
	exit 0
    else
	if [[ $maxattempts -eq -1 ]]; then 
	    sleep 1 
	    doPing 
	fi 
          ((attempts=attempts+1))
        if [[ $attempts -gt $maxattempts ]]; then
            showStatus "Failed to connect" 
            exit 1
        fi
	sleep 1
        doPing
    fi
}
showStatus "Waiting for network..."
doPing

