#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

echo "Installing..."

cd "$(dirname "$0")"

cp ./mcmr /usr/bin/
cp ./run_with_dots /usr/bin/
cp ./update /usr/bin/
cp ./checkwifi /usr/bin/ 
cp ./search /usr/bin 

echo "Successfully Installed!"
