#!/bin/bash

"$@" &
counter=0
sleep 1
while kill -0 $!; do
    echo -n '.' > /dev/tty
    sleep 1
    counter=$counter+1
    if [[ $counter -ge 3 ]]; then
        echo -n -e '\b\b\b   \b\b\b'
        counter=0
    fi
done

printf '\n' > /dev/tty