#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi
packagemanager="NONE"
updateflaak=""
yesflaak=""
distupgradeflaak=""
upgradeflaak=""
autoremoveflaak=""
logfile="/var/log/vo-utilities.log"
echo "[Log Start]" > $logfile

showStatus(){
    newline="\n"
    if [[ $2 == "silent" ]]; then
	newline=""
    fi 
    dt=$(date '+%H:%M:%S.%3N');
    echo -n -e "$dt Update > $1$newline"
}


echo "=============================================="
showStatus "Detecting Distro..."
lsb_release -i | grep -q "Ubuntu" &> $logfile 
if [ $? -eq 0 ]; then
   showStatus "Distro detected: Ubuntu"
   packagemanager="apt"
   updateflaak="update"
   yesflaak="-y"
   distupgradeflaak="dist-upgrade"
   upgradeflaak="upgrade"
   autoremoveflaak="autoremove"
fi
lsb_release -i | grep -q "Arch" &> $logfile 
if [ $? -eq 0 ]; then
   showStatus "Distro detected: Arch"
   packagemanager="pacman" 
    updateflaak="-Syyu"
    yesflaak="--noconfirm"
    distupgradeflaak=$updateflaak
    upgradeflaak=$updateflaak
    autoremoveflaak="-Qtdq " # Lists packages but doesn't remove them
fi

lsb_release -i | grep -q "Manjaro" &> $logfile 
if [ $? -eq 0 ]; then
   showStatus "Distro detected: Manjaro"
   packagemanager="pacman" 
    updateflaak="-Syyu"
    yesflaak="--noconfirm"
    distupgradeflaak=$updateflaak
    upgradeflaak=$updateflaak
    autoremoveflaak="-Qtdq " # Lists packages but doesn't remove them
fi

if [ $packagemanager == "NONE" ]; then
   echo "distro is not supported"
    showStatus "Unsupported distro detected. Closing..."
   exit 1
fi

showStatus "Starting update"
showStatus "Searching for packages that need updating" "silent"
run_with_dots $packagemanager $updateflaak $yesflaak &> $logfile 
if [ $? -eq 0 ]; then
    showStatus "Succeeded to search updated packages"
else
    showStatus "Failed to search updated packages"
    exit 1
fi


showStatus "Updating distro" "silent"
run_with_dots $packagemanager $distupgradeflaak $yesflaak &> $logfile 
if [ $? -eq 0 ]; then
    showStatus "Succeeded updating distro"
else
    showStatus "Failed updating distro. Closing..."
    exit 1
fi

showStatus "Updating packages" "silent"
run_with_dots $packagemanager $upgradeflaak $yesflaak &> $logfile 
if [ $? -eq 0 ]; then
    showStatus "Succeeded updating packages"
else
    showStatus "Failed updating packages. Closing..."
    exit 1
fi
showStatus "Removing old packages and files" "silent"
run_with_dots $packagemanager $autoremoveflaak $yesflaak  &> $logfile 
if [ $? -eq 0 ]; then
    showStatus "Succeeded removing old files"
else
    showStatus "Failed removing old files. Closing..."
    exit 1
fi
showStatus "System update successful."
echo "=============================================="
