#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi
packagemanager="NONE"
updateflaak=""
yesflaak=""
distupgradeflaak=""
upgradeflaak=""
autoremoveflaak=""

logfile="/var/log/vo-utilities.log"
echo "[Log Start]" > $logfile


lsb_release -i | grep -q "Ubuntu" &> $logfile 
if [ $? -eq 0 ]; then
   echo "DISTRO IS UBUNTU"
   packagemanager="apt"
   updateflaak="update"
   yesflaak="-y"
   distupgradeflaak="dist-upgrade"
   upgradeflaak="upgrade"
   autoremoveflaak="autoremove"
fi
lsb_release -i | grep -q "Arch" &> $logfile 
if [ $? -eq 0 ]; then
   echo "DISTRO IS ARCH"
    packagemanager="pacman" 
    updateflaak="-Syyu"
    yesflaak="--noconfirm"
    distupgradeflaak=$updateflaak
    upgradeflaak=$updateflaak
    autoremoveflaak="-Qtdq " # Lists packages but doesn't remove them
fi

if [ $packagemanager == "NONE" ]; then
   echo "DISTRO NOT SUPPORTED"
   exit 1
fi
echo "STARTING UPDATE"
$packagemanager $updateflaak $yesflaak &> $logfile 
if [ $? -eq 0 ]; then
    echo "SUCCEEDED TO SEARCH UPDATED PACKAGES"
else
    echo "FAILED TO SEARCH UPDATED PACKAGES"
    exit 1
fi
$packagemanager $distupgradeflaak $yesflaak &> $logfile 
if [ $? -eq 0 ]; then
    echo "SUCCEEDED UPDATING DISTRO"
else
    echo "FAILED UPDATING DISTRO"
    exit 1
fi
$packagemanager $upgradeflaak $yesflaak &> $logfile 
if [ $? -eq 0 ]; then
    echo "SUCCEEDED UPDATING PACKAGES"
else
    echo "FAILED UPDATING PACKAGES"
    exit 1
fi
$packagemanager $autoremoveflaak $yesflaak  &> $logfile 
if [ $? -eq 0 ]; then
    echo "SUCCEEDED REMOVING OLD FILES"
else
    echo "FAILED REMOVING OLD FILES"
    exit 1
fi
echo "DONE UPDATING SYSTEM"
